### ISSUE TITLE
Add Arc<CStr> to comparisons

### ISSUE THREAD

**Issue by agausmann** [jonhoo/arccstr#3]
Rust has [`impl From<&CStr> for Arc<CStr>`](https://doc.rust-lang.org/stable/src/std/ffi/c_str.rs.html#802-808), making this another feasible and comparable alternative to `ArcCStr`. The main difference between `Arc<CStr>` and `ArcCStr` is that `Arc<CStr>` has weak references and additional memory overhead from storing a weak reference count.

**Comment by jonhoo** [comment]
Ah, yes, I agree, that should be added! Would you mind sending a PR?

**Comment by agausmann** [comment]
Done! #4 , added Arc<str> while I was at it.
